// Copyright MadFall. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "MadBlockDefinitionJson.h"
#include "UObject/SoftObjectPath.h"

class FJsonObject;
class FMadBlockRegistry;

namespace MadFall
{
	inline const TCHAR* ItemSchemaV1 = TEXT("madfall.item/1");
	inline const TCHAR* RecipeSchemaV1 = TEXT("madfall.recipe/1");
	inline const TCHAR* LootSchemaV1 = TEXT("madfall.loot/1");
	inline const TCHAR* ZombieSchemaV1 = TEXT("madfall.zombie/1");
	inline const TCHAR* AnimalSchemaV1 = TEXT("madfall.animal/1");
	inline const TCHAR* QuestSchemaV1 = TEXT("madfall.quest/1");
	inline const TCHAR* TuningSchemaV1 = TEXT("madfall.tuning/1");
	inline const TCHAR* PerkSchemaV1 = TEXT("madfall.perk/1");
	inline const TCHAR* TraderSchemaV1 = TEXT("madfall.trader/1");
}

/** An item id and a count. The shape of every ingredient, output and repair cost. */
struct MADFALLCORE_API FMadItemAmount
{
	FName Item;
	int32 Count = 1;
};

enum class EMadItemKind : uint8
{
	Resource,
	Block,
	Tool,
	Weapon,
	Consumable,
	Mod
};

/** Tools and weapons. */
struct MADFALLCORE_API FMadToolStats
{
	/** Damage type -> hit points per use, e.g. "madfall:blunt": 25. */
	TMap<FName, float> Damage;

	/** Matched against a block's harvest tool_tags. A matching tool deals full damage and harvests drops. */
	TArray<FName> HarvestTags;

	/** Must be >= a block's harvest tier to harvest its drops. */
	int32 Tier = 0;

	/** Uses before breaking. 0 = unbreakable. */
	int32 Durability = 0;

	/** Seconds between uses. */
	float UseSeconds = 0.6f;

	float StaminaCost = 2.0f;

	/** Reach in voxels. */
	float Range = 4.0f;

	int32 ModSlots = 0;

	/** Items consumed by one repair action, and the fraction of max durability it restores. */
	TArray<FMadItemAmount> RepairWith;
	float RepairFraction = 0.25f;

	/** Ranged weapons: the item each shot uses up. NAME_None for melee. */
	FName Ammo;

	/** Launch speed, voxels per second. */
	float ProjectileSpeed = 45.0f;

	/** Fraction of normal gravity a shot falls with. */
	float ProjectileGravity = 0.5f;

	/** Chance a shot that hits the world can be picked up again. */
	float RecoverChance = 0.5f;

	bool IsRanged() const { return !Ammo.IsNone(); }
};

/** Food, drink, medicine. Effects are stat name -> instant delta ("health", "stamina", "food", "water", "infection", "temperature"). */
struct MADFALLCORE_API FMadConsumableStats
{
	float UseSeconds = 1.0f;
	TMap<FName, float> Effects;

	/** Given back after use - the empty bottle a drink leaves. */
	FName Returns;
};

/** Clothing and armour: an item worn in one of the four body slots. */
struct MADFALLCORE_API FMadWearStats
{
	/** "head", "body", "legs" or "feet". */
	FName Slot;

	/** Degrees of cold protection; the comfort band's lower edge drops by this much. */
	float Cold = 0.0f;

	/** Degrees of heat protection. */
	float Heat = 0.0f;

	/** Fraction of creature attack damage absorbed, 0-0.8. Worn pieces add up, to the same cap. */
	float Armor = 0.0f;
};

namespace MadFall::Wear
{
	inline constexpr int32 NumSlots = 4;

	/** Slot index 0-3 for "head", "body", "legs", "feet"; INDEX_NONE for anything else. */
	MADFALLCORE_API int32 GetSlotIndex(FName Slot);
	MADFALLCORE_API FName GetSlotName(int32 Index);

	/** Armour stops at this fraction however much is worn: nothing makes a survivor invulnerable. */
	inline constexpr float MaxArmor = 0.8f;
}

/** An attachable item mod. Multipliers are keyed by tool stat: "damage", "durability", "use_seconds", "stamina_cost", "range". */
struct MADFALLCORE_API FMadItemModStats
{
	TArray<FName> AppliesToTags;
	TMap<FName, float> Multipliers;
};

struct MADFALLCORE_API FMadItemDefinition
{
	FName Id;
	FName Extends;
	FString DisplayName;
	TArray<FName> Tags;

	EMadItemKind Kind = EMadItemKind::Resource;
	int32 MaxStack = 100;

	/** True when a file set max_stack, so a tool left at the default is not reported as a stackable tool. */
	bool bMaxStackExplicit = false;

	float WeightKg = 0.1f;
	FSoftObjectPath Icon;

	/** What a trader asks for one, in the trader's currency. 0: traders neither sell nor buy it unless their stock names a price. */
	int32 Value = 0;

	/** Placing this item writes that block. Set on every block item. */
	FName PlacesBlock;

	/** Right-clicking water with this item turns one into that item (an empty bottle into murky water). */
	FName FillsInto;

	/** Right-clicking a `block.tillable` block with this item turns it into that block (a hoe makes farmland). */
	FName TillsInto;

	bool bHasTool = false;
	FMadToolStats Tool;

	bool bHasConsumable = false;
	FMadConsumableStats Consumable;

	bool bHasWear = false;
	FMadWearStats Wear;

	bool bHasMod = false;
	FMadItemModStats Mod;

	/** True for block items the registry generated because no file defined them. */
	bool bAutoGenerated = false;

	FName SourceModId;
	FString SourcePath;

	bool HasTag(FName Tag) const { return Tags.Contains(Tag); }
};

struct MADFALLCORE_API FMadRecipeDefinition
{
	FName Id;
	FMadItemAmount Output;
	TArray<FMadItemAmount> Ingredients;

	/** Crafting station id, e.g. "madfall:workbench". NAME_None crafts from the backpack. */
	FName Station;

	float CraftSeconds = 1.0f;
	int32 RequiredLevel = 0;
	TArray<FName> Tags;

	FName SourceModId;
	FString SourcePath;
};

/** One weighted choice in a loot table. Exactly one of Item and Table is set. */
struct MADFALLCORE_API FMadLootEntry
{
	FName Item;
	FName Table;
	float Weight = 1.0f;
	int32 CountMin = 1;
	int32 CountMax = 1;

	/** POI tier window, inclusive. */
	int32 MinTier = 0;
	int32 MaxTier = 99;

	/** Game stage (days survived plus player level) this entry unlocks at. */
	int32 MinGameStage = 0;

	/** Durability of dropped tools, as a fraction of max. */
	float DurabilityMin = 1.0f;
	float DurabilityMax = 1.0f;

	/** Given on every roll of the table, outside the weighted pick: a crop always yields its seeds. */
	bool bAlways = false;
};

struct MADFALLCORE_API FMadLootTableDefinition
{
	FName Id;
	int32 RollsMin = 1;
	int32 RollsMax = 1;

	/** Extra rolls per POI tier above 1. Fractions accumulate: 0.5 is one extra roll per two tiers. */
	float RollsPerTier = 0.0f;

	/** Weight of rolling nothing at all. */
	float EmptyWeight = 0.0f;

	TArray<FMadLootEntry> Entries;

	FName SourceModId;
	FString SourcePath;
};

/**
 * A named set of numbers the game reads by key - survival rates, for now.
 *
 * Deliberately a flat map rather than a typed struct in Core: the consumer
 * (Gameplay) owns what the keys mean and reports unknown ones, and a mod
 * rebalancing hunger writes one patch op instead of learning a new schema.
 */
struct MADFALLCORE_API FMadTuningDefinition
{
	FName Id;
	TMap<FName, float> Values;

	FName SourceModId;
	FString SourcePath;
};

/** One rank of a perk: the level it unlocks at, and the stat multipliers it grants. */
struct MADFALLCORE_API FMadPerkRank
{
	int32 RequiredLevel = 1;

	/** Stat name -> multiplier applied while this rank is owned (ranks do not stack; the highest owned rank applies). */
	TMap<FName, float> Modifiers;

	/**
	 * Perk id -> rank of that perk the survivor must already own to buy this
	 * rank ("requires": { "madfall:athlete": 1 }). Per rank, not per perk, so a
	 * perk can open freely and gate only its top ranks - that is what makes a
	 * tree out of a flat list. Unknown perks, ranks a perk does not have and
	 * cycles are reported and removed at load, so no rank can be locked forever.
	 */
	TMap<FName, int32> Requires;
};

/** A perk the survivor spends level-up points on. */
struct MADFALLCORE_API FMadPerkDefinition
{
	FName Id;
	FString DisplayName;
	FString Description;
	TArray<FName> Tags;
	TArray<FMadPerkRank> Ranks;

	FName SourceModId;
	FString SourcePath;
};

/**
 * A zombie variant.
 *
 * Variants are data, not subclasses: a brute is a civilian with more health,
 * more block damage and a bigger scale. Spawn groups are memberships listed on
 * the variant, so a mod adds a zombie to POI spawns or hordes by naming the
 * group, without touching the prefab or the director.
 */
struct MADFALLCORE_API FMadZombieDefinition
{
	FName Id;
	FString DisplayName;
	TArray<FName> Tags;

	/** e.g. "madfall:zombies/civilian", "madfall:zombies/horde". */
	TArray<FName> SpawnGroups;
	float SpawnWeight = 1.0f;
	int32 MinGameStage = 0;

	float Health = 100.0f;

	/** Metres per second. */
	float WalkSpeed = 1.4f;
	float RunSpeed = 3.2f;

	float AttackDamage = 8.0f;

	/** Hit points dealt to a block per attack while digging. */
	float BlockDamage = 20.0f;
	float AttackSeconds = 1.2f;
	FName DamageType = FName(TEXT("madfall:blunt"));

	/** Infection added to the player per landed hit. */
	float InfectionPerHit = 3.0f;

	/** Voxels. */
	float SightRange = 24.0f;
	float HearingRange = 40.0f;

	int32 Experience = 25;
	FName LootTable;

	float Scale = 1.0f;
	/** Skin colour, linear (authored as sRGB in appearance.tint). */
	FLinearColor Tint = FLinearColor(0.10f, 0.17f, 0.07f);

	/** abilities.ranged: spits at a target it can see within RangedRange voxels. 0 damage = no ranged attack. */
	float RangedDamage = 0.0f;
	float RangedRange = 0.0f;
	float RangedSeconds = 3.0f;
	/** Voxels per second. */
	float RangedSpeed = 22.0f;

	/** abilities.scream: on sighting a target, alerts zombies within ScreamRadius voxels and calls ScreamSummons more. */
	float ScreamRadius = 0.0f;
	float ScreamSeconds = 45.0f;
	int32 ScreamSummons = 0;

	/** abilities.climbs_walls: climbs straight up any wall toward a target, like a ladder. */
	bool bClimbsWalls = false;

	/**
	 * Damage multipliers by damage type ("resistances"), as blocks have: 0.5
	 * takes half, 1.5 half again more, a type not listed 1. An armoured
	 * soldier shrugs off arrows; a bloater bursts on them.
	 */
	TMap<FName, float> Resistances;

	float GetDamageMultiplier(FName IncomingType) const
	{
		const float* Found = Resistances.Find(IncomingType);
		return Found != nullptr ? FMath::Max(0.0f, *Found) : 1.0f;
	}

	bool HasRanged() const { return RangedDamage > 0.0f && RangedRange > 0.0f; }
	bool HasScream() const { return ScreamRadius > 0.0f; }

	FName SourceModId;
	FString SourcePath;
};

/** How an animal reacts to the survivor. */
enum class EMadAnimalBehaviour : uint8
{
	/** Runs from a survivor it sees close by or hears, and from anything that hurts it. */
	Skittish,
	/** Grazes until hurt, then fights back until the survivor is out of reach. */
	Defensive,
	/** Hunts a survivor it sees. */
	Aggressive
};

/** When an animal is about. */
enum class EMadAnimalActivity : uint8
{
	Always,
	Day,
	Night
};

/**
 * Wildlife: something to hunt for meat and hide, and something that hunts back.
 *
 * A separate kind from zombies rather than a zombie variant: animals never dig,
 * never join a horde, spawn by biome instead of by POI group, and run away. What
 * they share with zombies - pathing, senses, a loot bag on death - is shared in
 * code, not in the schema.
 */
/**
 * An animated skeletal model an animal is drawn with (appearance.model), instead
 * of the figure built from its body proportions.
 *
 * WHY THE PATHS ARE DATA: the shipped deer and wolf come from one CC0 pack whose
 * clips are named per animal (DeerGallop, WolfAttack), and a mod's animal will
 * come from anywhere. Naming each clip's role keeps the rig from guessing, and
 * leaving a role out (a deer model with no attack clip, say)
 * just means that moment is not animated.
 */
struct MADFALLCORE_API FMadAnimalModel
{
	FSoftObjectPath Mesh;
	FSoftObjectPath Idle;
	FSoftObjectPath Walk;
	FSoftObjectPath Run;
	FSoftObjectPath Attack;
	FSoftObjectPath Hit;
	FSoftObjectPath Death;
	FSoftObjectPath Graze;

	/** Ground speed, m/s, at which the walk and run cycles play at their authored rate, so the feet keep pace. */
	float WalkCycleSpeed = 1.2f;
	float RunCycleSpeed = 6.0f;

	/** Degrees the model is turned about Z so its head points along the animal's forward (+X). */
	float Yaw = 0.0f;

	/** A mesh and the two clips an animal cannot do without. */
	bool IsSet() const { return !Mesh.IsNull() && !Idle.IsNull() && !Walk.IsNull(); }
};

struct MADFALLCORE_API FMadAnimalDefinition
{
	FName Id;
	FString DisplayName;
	TArray<FName> Tags;

	/** Biome ids this animal spawns in. */
	TArray<FName> Biomes;
	float SpawnWeight = 1.0f;
	int32 HerdMin = 1;
	int32 HerdMax = 1;
	EMadAnimalActivity Activity = EMadAnimalActivity::Always;

	EMadAnimalBehaviour Behaviour = EMadAnimalBehaviour::Skittish;

	float Health = 40.0f;

	/** Metres per second. */
	float WalkSpeed = 1.2f;
	float RunSpeed = 5.0f;

	float AttackDamage = 0.0f;
	float AttackSeconds = 1.2f;
	FName DamageType = FName(TEXT("madfall:blunt"));

	/** Voxels. Flee is how close a seen survivor may come before a skittish animal bolts. */
	float SightRange = 18.0f;
	float HearingRange = 24.0f;
	float FleeRange = 10.0f;

	int32 Experience = 10;
	FName LootTable;

	/** Torso length, width, height; leg and neck length. Centimetres, before Scale. */
	FVector BodySize = FVector(90.0, 32.0, 40.0);
	float LegLength = 45.0f;
	float NeckLength = 25.0f;
	float Scale = 1.0f;

	/** Coat colour, linear (authored as sRGB in appearance.tint). */
	FLinearColor Tint = FLinearColor(0.2f, 0.12f, 0.06f);

	/** Drawn instead of the proportioned figure when set and its assets load; sized to the proportions above. */
	FMadAnimalModel Model;

	FName SourceModId;
	FString SourcePath;

	bool IsActive(bool bNight) const
	{
		return Activity == EMadAnimalActivity::Always || (Activity == EMadAnimalActivity::Night) == bNight;
	}
};

/** What a quest objective counts. */
enum class EMadQuestObjectiveType : uint8
{
	/** Items finished at a crafting queue. */
	Craft,
	/** Items held at once (checked, not counted: dropping them undoes it). */
	Have,
	/** Blocks placed. */
	Place,
	/** Blocks broken by the survivor. */
	Break,
	KillZombie,
	KillAnimal,
	/** Clothing put on. */
	Wear,
	/** A bed slept in. */
	SetSpawn,
	/** The clock reaching a day (Count). */
	ReachDay,
	/** Trades made with a trader (Target: the trader id). */
	Trade,
	/**
	 * Zombies killed that a POI woke, counted against the POI they came from
	 * (Target: a prefab id, Tag: one of the prefab's tags).
	 *
	 * WHY this is not KillZombie with a tag: a zombie's own definition says
	 * what it is, not where it was standing. Clearing a building is the one
	 * job in the game that is about a place, so the event carries the place.
	 */
	ClearPoi
};

struct MADFALLCORE_API FMadQuestObjective
{
	EMadQuestObjectiveType Type = EMadQuestObjectiveType::Craft;

	/** An exact item, block, zombie or animal id. NAME_None matches any. */
	FName Target;

	/** A tag the thing must carry. NAME_None matches any. */
	FName Tag;

	int32 Count = 1;

	/** "@key" or literal text for the journal; generated from the rest when empty. */
	FString Text;

	/** True if an event about Id with Tags counts toward this objective. */
	bool Matches(FName Id, const TArray<FName>& Tags) const
	{
		return (Target.IsNone() || Target == Id) && (Tag.IsNone() || Tags.Contains(Tag));
	}
};

/** One line of what a trader carries. */
struct MADFALLCORE_API FMadTraderStockEntry
{
	FName Item;
	int32 CountMin = 1;
	int32 CountMax = 1;

	/** Price for one; 0 uses the item's value. */
	int32 Price = 0;

	/** Chance the line is in stock at a restock. */
	float Chance = 1.0f;
};

/**
 * A trader: who stands at a trader marker, what they sell and what they pay.
 *
 * Stock is rolled per trader position and restocked every RestockDays, so each
 * outpost has its own shelves. A trader buys any item with a value (or, with
 * BuysTags, only items carrying one of those tags) for BuyFactor of it: a
 * player can turn loot into currency, never at a profit.
 */
struct MADFALLCORE_API FMadTraderDefinition
{
	FName Id;
	FString DisplayName;

	/** Shown when the trade screen opens. */
	FString Greeting;

	FName Currency = FName(TEXT("madfall:coin"));
	TArray<FMadTraderStockEntry> Stock;

	float BuyFactor = 0.25f;
	TArray<FName> BuysTags;
	int32 RestockDays = 3;

	FName SourceModId;
	FString SourcePath;
};

/**
 * A quest: objectives, what unlocks it, what it pays.
 *
 * Quests are data like everything else so the tutorial ships as a mod would,
 * and a mod adds a quest line by naming shipped quests in `requires`. There is
 * no giver: a quest starts the moment everything it requires is done.
 */
struct MADFALLCORE_API FMadQuestDefinition
{
	FName Id;
	FString DisplayName;
	FString Description;

	/** Quests that must be complete first. */
	TArray<FName> Requires;

	TArray<FMadQuestObjective> Objectives;

	int32 RewardExperience = 0;
	TArray<FMadItemAmount> RewardItems;

	/** Journal order among quests active at once; lower first. */
	int32 Order = 0;

	FName SourceModId;
	FString SourcePath;
};

/**
 * Items, recipes and loot tables.
 *
 * One registry for three kinds because they are validated against each other:
 * a recipe that names an item nobody defines, or a loot table that points at a
 * missing table, is a load-time error with a file and a JSON pointer - never a
 * crafting menu entry that silently does nothing.
 *
 * LIFECYCLE mirrors the block registry: BeginLoad, Add*, FinishLoad. FinishLoad
 * takes the block registry because every placeable block gets an item: a mod
 * that adds a block gets a craftable, placeable, lootable item for it without
 * writing one. An explicit item with the block's id replaces the generated one.
 *
 * INHERITANCE: items support `extends` (tool families share stats). Recipes and
 * loot tables do not - their bodies are arrays, and arrays replace on
 * inheritance anyway, so `extends` would only ever inherit a name.
 */
class MADFALLCORE_API FMadGameplayDefinitions
{
public:
	void BeginLoad();

	int32 AddItemsFromDirectory(const FString& Directory, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	int32 AddRecipesFromDirectory(const FString& Directory, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	int32 AddLootFromDirectory(const FString& Directory, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	int32 AddZombiesFromDirectory(const FString& Directory, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	int32 AddAnimalsFromDirectory(const FString& Directory, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	int32 AddQuestsFromDirectory(const FString& Directory, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	int32 AddTuningFromDirectory(const FString& Directory, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	int32 AddPerksFromDirectory(const FString& Directory, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	int32 AddTradersFromDirectory(const FString& Directory, FName ModId, TArray<FMadDefinitionError>& OutErrors);

	/** Stage one JSON object directly. For tests and tools. */
	bool AddItemJson(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	bool AddRecipeJson(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	bool AddLootJson(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	bool AddZombieJson(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	bool AddAnimalJson(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	bool AddQuestJson(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	bool AddTuningJson(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	bool AddPerkJson(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId, TArray<FMadDefinitionError>& OutErrors);
	bool AddTraderJson(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId, TArray<FMadDefinitionError>& OutErrors);

	/** Resolves inheritance, generates block items, validates cross references. Blocks may be null (no block items). */
	void FinishLoad(const FMadBlockRegistry* Blocks, TArray<FMadDefinitionError>& OutErrors);

	/** Applies mod patches to every staged item, recipe, loot table and zombie. Call before FinishLoad. */
	void ApplyPatches(const class FMadPatchSet& Patches, TArray<FMadDefinitionError>& OutErrors);

	const FMadItemDefinition* FindItem(FName Id) const;
	const FMadRecipeDefinition* FindRecipe(FName Id) const;
	const FMadLootTableDefinition* FindLootTable(FName Id) const;
	const FMadZombieDefinition* FindZombie(FName Id) const;
	const FMadAnimalDefinition* FindAnimal(FName Id) const;
	const FMadQuestDefinition* FindQuest(FName Id) const;
	const FMadTuningDefinition* FindTuning(FName Id) const;
	const FMadPerkDefinition* FindPerk(FName Id) const;
	const FMadTraderDefinition* FindTrader(FName Id) const;

	/** What a trader charges for one of an item, or 0 if they do not sell it. */
	int32 GetTraderPrice(const FMadTraderDefinition& Trader, FName ItemId) const;

	/** What a trader pays for one of an item, or 0 if they will not buy it. */
	int32 GetTraderOffer(const FMadTraderDefinition& Trader, FName ItemId) const;

	/** Variants in a spawn group that are unlocked at a game stage. */
	void GetZombiesInGroup(FName Group, int32 GameStage, TArray<const FMadZombieDefinition*>& OutZombies) const;

	/** The item that places a block, or nullptr. */
	const FMadItemDefinition* FindItemForBlock(FName BlockId) const;

	/**
	 * Player-facing names, localized (see FMadStringTable). An id nothing defines
	 * - a removed mod's item - still reads as a name made from the id.
	 */
	FString GetItemName(FName ItemId) const;
	FString GetPerkName(FName PerkId) const;
	static FString GetBlockName(FName BlockId);

	/** Sorted by id. */
	const TArray<FMadItemDefinition>& GetItems() const { return Items; }
	const TArray<FMadRecipeDefinition>& GetRecipes() const { return Recipes; }
	const TArray<FMadLootTableDefinition>& GetLootTables() const { return LootTables; }
	const TArray<FMadZombieDefinition>& GetZombies() const { return Zombies; }
	const TArray<FMadAnimalDefinition>& GetAnimals() const { return Animals; }
	const TArray<FMadQuestDefinition>& GetQuests() const { return Quests; }
	const TArray<FMadPerkDefinition>& GetPerks() const { return Perks; }
	const TArray<FMadTraderDefinition>& GetTraders() const { return Traders; }

	/** Recipes producing an item. */
	void FindRecipesFor(FName ItemId, TArray<const FMadRecipeDefinition*>& OutRecipes) const;

	FString DescribeContents() const;

private:
	struct FPendingItem
	{
		FName Id;
		FName Extends;
		FName ModId;
		FString SourcePath;
		TSharedPtr<FJsonObject> Json;
	};

	bool ResolveItem(FName Id, TSet<FName>& Visiting, TMap<FName, FMadItemDefinition>& Resolved, TArray<FMadDefinitionError>& OutErrors);

	TArray<FPendingItem> PendingItems;
	TMap<FName, int32> PendingItemIndex;

	TMap<FName, FMadRecipeDefinition> PendingRecipes;
	TMap<FName, FMadLootTableDefinition> PendingLoot;
	TMap<FName, FMadZombieDefinition> PendingZombies;
	TMap<FName, FMadAnimalDefinition> PendingAnimals;
	TMap<FName, FMadQuestDefinition> PendingQuests;

	/** Source JSON kept beside the parsed data, so patches can edit it and re-parse. */
	TMap<FName, FPendingItem> RecipeSources;
	TMap<FName, FPendingItem> LootSources;
	TMap<FName, FPendingItem> ZombieSources;
	TMap<FName, FPendingItem> AnimalSources;
	TMap<FName, FPendingItem> QuestSources;
	TMap<FName, FMadTuningDefinition> PendingTuning;
	TMap<FName, FPendingItem> TuningSources;
	TMap<FName, FMadPerkDefinition> PendingPerks;
	TMap<FName, FPendingItem> PerkSources;
	TMap<FName, FMadTraderDefinition> PendingTraders;
	TMap<FName, FPendingItem> TraderSources;

	TArray<FMadItemDefinition> Items;
	TArray<FMadRecipeDefinition> Recipes;
	TArray<FMadLootTableDefinition> LootTables;
	TArray<FMadZombieDefinition> Zombies;
	TArray<FMadAnimalDefinition> Animals;
	TArray<FMadQuestDefinition> Quests;
	TArray<FMadTuningDefinition> Tunings;
	TArray<FMadPerkDefinition> Perks;
	TArray<FMadTraderDefinition> Traders;

	TMap<FName, int32> ItemIndex;
	TMap<FName, int32> RecipeIndex;
	TMap<FName, int32> LootIndex;
	TMap<FName, int32> ZombieIndex;
	TMap<FName, int32> AnimalIndex;
	TMap<FName, int32> QuestIndex;
	TMap<FName, int32> TuningIndex;
	TMap<FName, int32> PerkIndex;
	TMap<FName, int32> TraderIndex;
	TMap<FName, int32> BlockToItem;
};

namespace MadFall
{
	/**
	 * The process-wide gameplay definitions, built on first use from
	 * Definitions/{items,recipes,loot} and every mod's equivalents, validated
	 * against the block registry.
	 */
	MADFALLCORE_API FMadGameplayDefinitions& GetGameplayDefinitions();

	namespace GameplayDefinitionsJson
	{
		MADFALLCORE_API bool ParseItem(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId,
			FMadItemDefinition& InOutData, TArray<FMadDefinitionError>& OutErrors);

		MADFALLCORE_API bool ParseRecipe(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId,
			FMadRecipeDefinition& OutData, TArray<FMadDefinitionError>& OutErrors);

		MADFALLCORE_API bool ParseLootTable(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId,
			FMadLootTableDefinition& OutData, TArray<FMadDefinitionError>& OutErrors);

		MADFALLCORE_API bool ParseZombie(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId,
			FMadZombieDefinition& OutData, TArray<FMadDefinitionError>& OutErrors);

		MADFALLCORE_API bool ParseAnimal(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId,
			FMadAnimalDefinition& OutData, TArray<FMadDefinitionError>& OutErrors);

		MADFALLCORE_API bool ParseQuest(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId,
			FMadQuestDefinition& OutData, TArray<FMadDefinitionError>& OutErrors);

		MADFALLCORE_API bool ParseTuning(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId,
			FMadTuningDefinition& OutData, TArray<FMadDefinitionError>& OutErrors);

		MADFALLCORE_API bool ParsePerk(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId,
			FMadPerkDefinition& OutData, TArray<FMadDefinitionError>& OutErrors);

		MADFALLCORE_API bool ParseTrader(const TSharedRef<FJsonObject>& Object, const FString& SourcePath, FName ModId,
			FMadTraderDefinition& OutData, TArray<FMadDefinitionError>& OutErrors);
	}
}
